spring:
#数据库配置
  datasource:
    url: jdbc:mysql://10.130.70.11:3306/jac_tboss?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Jac_prod_rds01
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 80
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

dms:
  workOrderReportUrl: getClwRoInfo.wsServer.ws.dms.infoservice.com/NewOperation
mes:
  vehicleProductSearchUrl: http://59.48.146.132:50000/RESTAdapter/ClpzcxTest
#xxl-job configuration
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    accessToken:
    executor:
      appname: jac-nut-app-job
      address:
      ip:
      port: 10520
      logpath: /opt/jac/backend/app/app-jobs/logs
      logretentiondays: 30
    admin:
     addresses: http://10.130.50.53:9080/xxl-job-admin



#招商银行请求地址
cmb:
  baseUrl: https://api.cmbchina.com/ptn/api
#招行appid
  appId: 174b477b-11c4-4ac8-a1ce-c90fe62f67c9
#招行appSecret
  appSecret: 6a42d519-2620-4429-91f9-c1ae64a3cab0
#商户私钥（国密SM2）
  sm2_private_key: E72648F8E8ADA68615DD71D83EA3118E1B1AF4ADC580A18EEABF522BF7AAECE2
#招行公钥（国密SM2）
  sm2_cmb_public_key: MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEI2JuBTsKz9bAJudAxaGEAshoYFTOAGs2XQzGg93NlW67em9KSacSd0z0KVHsV87JtO38ZrEExHw7+qSCB3Qmsw==
#回调地址（一网通）
  notify_url_netpay: http://jacwxmp.starnetah.com:16666/driver/paySimCard/notify/netpay
#回调地址（支付宝）
  notify_url_alipay: http://jacwxmp.starnetah.com:16666/driver/paySimCard/pay/notify/alipay
#回调地址（微信）
  notify_url_wechat: http://jacwxmp.starnetah.com:16666/driver/paySimCard/pay/notify/wechat
#回调地址（支付宝/微信退款）
  refund_notify_url: http://jacwxmp.starnetah.com:16666/driver/mgr/order/refund/notify
#商户号
  mer_id: 30899915511007Z
#收银员号
  user_id: N087284002
#子商户号
  sub_mer_id: 308999155110083
#子门店号
  sub_store_id: 3089991551100830001
#开放平台appid（微信）
  wechat_appid: wx88297831a71c80e3
  #\u5546\u6237\u53F7\uFF08\u5FAE\u4FE1\u5C0F\u7A0B\u5E8F\uFF09
  wechat_mini_mer_id: 30899915511007Z
  #\u6536\u94F6\u5458\u53F7\uFF08\u5FAE\u4FE1\u5C0F\u7A0B\u5E8F\uFF09
  wechat_mini_user_id: N087284002
  #\u5B50\u5546\u6237\u53F7\uFF08\u5FAE\u4FE1\u5C0F\u7A0B\u5E8F\uFF09
  wechat_mini_sub_mer_id: 308999155110083
#\u5B50\u95E8\u5E97\u53F7\uFF08\u5FAE\u4FE1\u5C0F\u7A0B\u5E8F\uFF09
  wechat_mini_sub_store_id: 3089991551100830001
#商户号（微信）
  wechat_mer_id: 30899915511007Z
#收银员号（微信）
  wechat_user_id: N087284002
#子商户号（微信）
  wechat_sub_mer_id: 308999155110083
#子门店号（微信）
  wechat_sub_store_id: 3089991551100830001
