server:
  port: 8027

#服务名称
spring:
  application:
    name: jac-nut-app-kafka
  profiles:
    active: dev
  metrics:
    export:
      includes: '*'

#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.248:7000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#feign\u63A5\u53E3\u8D85\u65F6\u8BBE\u7F6E
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  #\u5168\u5C40\u914D\u7F6E\uFF0Cfeign\u8C03\u7528\u5176\u4ED6\u5FAE\u670D\u52A1\u8D85\u65F6\u8BBE\u7F6E\uFF0C\u9ED8\u8BA4\u4E3A1\u79D2
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

nut:
  monitor:
    profile: jac-test
management:
  port: 21403
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false
  context-path: /
